analyzer: 
  cmd: ./lib/goosli --cmd=analyze --settings=settings.yaml
  result: analyze_triangles.txt
colorizer: 
  cmd: ./lib/goosli --cmd=colorize --settings=settings.yaml
  color: Red
  result: colorize_triangles.bin
colors: 
  background: SlateGray
  blue: Blue
  last_layer: Red
  layer: White
  plane: Cyan
  splane: Gold
common: 
  lang: ru
  splane_diameter: 150
hardware: 
  bar_diameter: 1.75
  calibration_x: 
    a0: 0
    a10: -0.13
    a20: -0.18
    a30: -0.3
    a40: -0.37
    a50: -0.42
  flow: 1.0
  plane_center_x: 0
  plane_center_y: 0
  plane_center_z: 0
  plane_diameter: 250
  rotation_center_x: 0
  rotation_center_y: 0
  rotation_center_z: 63.5
slicing: 
  angle: 30
  bed_temperature: 60
  bottom_layers: 3
  bottom_of_cut_layers: 1
  cmd: ./lib/goosli --cmd=slice --settings=settings.yaml
  extruder_temperature: 200
  fan_off_layer1: false
  fan_speed: 95
  fill_density: 20
  filling_type: Triangles
  flat_5d: 0
  ftetwild_cmd: ./lib/FloatTetwild_bin.exe -i sett.slicing.stl_file -o lib/goosli_middle.msh
  gcode_file: goosli_out.gcode
  layer_height: 0.2
  line_width: 0.4
  mesh_file: lib/goosli_middle.msh
  originx: 0.25125885009765625
  originy: -1.6277618408203125
  originz: 1.627760410308838
  print_speed: 50
  print_speed_layer1: 50
  print_speed_wall: 50
  retraction_distance: 0.3
  retraction_on: true
  retraction_speed: 50
  rotationx: 0.0
  rotationy: -0.0
  rotationz: 0.0
  scalex: 1.0
  scaley: 1.0
  scalez: 1.0
  skirt_line_count: 3
  slicing_type: vip
  smooth_cmd: ./FASP.exe
  splanes_file: lib/planes_file.txt
  stl_file: D:\y.stl
  support_offset: 1.0
  supports_on: false
  t_geodesic: 0.0
  wall_thickness: 0.8