analyzer: 
  cmd: ./goosli --cmd=analyze --settings=settings.yaml
  result: analyze_triangles.txt
colorizer: 
  cmd: ./goosli --cmd=colorize --settings=settings.yaml
  color: Red
  result: colorize_triangles.bin
colors: 
  background: SlateGray
  blue: Blue
  last_layer: Red
  layer: White
  plane: Cyan
  splane: Gold
common: 
  lang: ru
  splane_diameter: 150
hardware: 
  bar_diameter: 1.75
  flow: 1.0
  plane_center_x: 0
  plane_center_y: 0
  plane_center_z: 0
  plane_diameter: 250
  rotation_center_x: 0
  rotation_center_y: 0
  rotation_center_z: 50
slicing: 
  angle: 30
  bed_temperature: 60
  bottom_layers: 3
  cmd: ./goosli --cmd=slice --settings=settings.yaml
  extruder_temperature: 200
  fan_off_layer1: false
  fan_speed: 95
  fill_density: 20
  filling_type: Triangles
  ftetwild_cmd: ./FloatTetwild_bin.exe -i sett.slicing.stl_file -o goosli_middle.msh
  gcode_file: goosli_out.gcode
  layer_height: 0.2
  line_width: 0.4
  mesh_file: goosli_middle.msh
  originx: 34.18250175443659
  originy: -16.98024240363457
  originz: 17.538703082138134
  print_speed: 50
  print_speed_layer1: 50
  print_speed_wall: 50
  retraction_distance: 0.3
  retraction_on: true
  retraction_speed: 50
  rotationx: -29.590723233365974
  rotationy: 13.884527594674974
  rotationz: 41.99918568990012
  scalex: 0.9999999999999971
  scaley: 1.0000000000000013
  scalez: 0.999999999999997
  skirt_line_count: 3
  slicing_type: vip
  smooth_cmd: ./FASP.exe
  splanes_file: planes_file.txt
  stl_file: /home/l1va/Downloads/5axes_3d_printer/test/1_odn2.stl
  support_offset: 1.0
  supports_on: false
  top_layers: 3
  wall_thickness: 0.8