analyzer: 
  cmd: ./goosli --cmd=analyze --settings=settings.yaml
  result: analyze_triangles.txt
colorizer: 
  cmd: ./goosli --cmd=colorize --settings=settings.yaml
  color: Red
  result: colorize_triangles.bin
colors: 
  background: SlateGray
  blue: Blue
  last_layer: Red
  layer: White
  plane: Cyan
  splane: Gold
common: 
  lang: ru
  splane_diameter: 150
hardware: 
  bar_diameter: 1.75
  flow: 1.0
  plane_center_x: 0
  plane_center_y: 0
  plane_center_z: 0
  plane_diameter: 250
  rotation_center_x: 0
  rotation_center_y: 0
  rotation_center_z: 63.5
slicing: 
  angle: 30
  bed_temperature: 60
  bottom_layers: 3
  cmd: ./goosli --cmd=slice --settings=settings.yaml
  extruder_temperature: 200
  fan_off_layer1: false
  fan_speed: 95
  fill_density: 20
  filling_type: Triangles
  ftetwild_cmd: ./FloatTetwild_bin.exe -i sett.slicing.stl_file -o goosli_middle.msh
  gcode_file: goosli_out.gcode
  layer_height: 0.2
  line_width: 0.4
  mesh_file: goosli_middle.msh
  originx: 43.26799957111282
  originy: 38.55473017684402
  originz: 15.668192441495945
  print_speed: 50
  print_speed_layer1: 50
  print_speed_wall: 50
  retraction_distance: 0.3
  retraction_on: true
  retraction_speed: 50
  rotationx: -3.572603488368519
  rotationy: 17.17415365142365
  rotationz: 75.32477813368416
  scalex: 0.9999999999999998
  scaley: 1.0000000000000013
  scalez: 1.0000000000000007
  skirt_line_count: 3
  slicing_type: 3axes
  smooth_cmd: ./FASP.exe
  splanes_file: planes_file.txt
  stl_file: /home/l1va/Downloads/5axes_3d_printer/test/___odnbez.stl
  support_offset: 1.0
  supports_on: false
  top_layers: 3
  wall_thickness: 0.8