colorizer:
  cmd: ./lib/goosli --cmd=colorize --settings=
  color: Red
  copy_stl_file: ./copy_stl_file.stl
  result: colorize_triangles.bin
colors:
  background: SlateGray
  blue: Blue
  last_layer: Red
  layer: DarkSlateGray
  plane: Cyan
  splane: Cyan
  edge: Orange
  model: Silver
common:
  lang: ru
  opacity_current_plane: 0.8
  opacity_last_layer: 1.0
  opacity_layer: 0.8
  opacity_plane: 0.3
  opacity_table: 0.3
  splane_diameter: 150
  version: v1.0.0
hardware:
  printer_dir: ""
  bar_diameter: 1.75
  calibration_file: calibration_data.csv
  calibration_file_zero: data/calibration_data_zero.csv
  calibration_x:
    a0: 0
    a10: -0.13
    a20: -0.18
    a30: -0.3
    a40: -0.37
    a50: -0.42
  density: 1.23
  flow: 1.0
  plane_center_x: 0
  plane_center_y: 0
  plane_center_z: 0
  plane_diameter: 250
  maximum_height: 240
  minimum_planner_speed: 0.05
  nozzle_contact_points:
    x0: 0.5
    x1: 2.8
    x2: 30.0
    y0: 0.0
    y1: 3.3
    y2: 53.7
  rotation_center_x: 0
  rotation_center_y: 0
  rotation_center_z: 63.5
  # maximum speed in mm/min for linear exes, in deg/min for rotational
  max_speed:
    X: 2000
    Y: 2000
    Z: 2000
    U: 500
    V: 500
    E: 2000
  # acceleration in mm/s^2 for linear exes, in deg/s^2 for rotational
  acceleration:
    X: 800
    Y: 800
    Z: 800
    U: 300
    V: 300
    E: 1000
  # maximum jerk in mm/min for linear exes, in deg/min for rotational
  max_jerk:
    X: 200
    Y: 200
    Z: 200
    U: 200
    V: 200
    E: 120
slicing:
  angle: 30
  bed_temperature: 60
  bottom_of_cut_layers: 1
  cmd: ./lib/goosli --cmd=slice --settings=
  cmd_version: ./lib/goosli --version
  consumption_material: 0
  extruder_temperature: 200
  fan_off_layer1: false
  fan_speed: 95
  fill_density: 20
  filling_type: Triangles
  filter_tolerance: 0.01
  flat_5d: 0
  ftetwild_cmd: ./lib/FloatTetwild_bin.exe -i sett.slicing.stl_file -o lib/goosli_middle.msh
  gcode_file: goosli_out.gcode
  gcode_file_without_calibration: goosli_out_without_calibration.gcodevis
  layer_height: 0.2
  lids_depth: 3
  bottoms_depth: 3
  line_width: 0.4
  magic_epsilon: 40
  material_shrinkage: 1.5
  mesh_file: lib/goosli_middle.msh
  minimum_path_area: 0.001
  model_centering: false
  originx: 0.0
  originy: 0.0
  originz: 0.0
  overlapping_infill_percentage: 100.0
  overlapping_infill_lid_percentage: 60.0
  planes_contact_with_nozzle: ""
  print_speed: 50
  print_speed_layer1: 50
  print_speed_wall: 50
  print_time: 0
  retract_compensation_amount: 0.0
  retraction_distance: 0.3
  retraction_on: true
  retraction_speed: 50
  rotationx: 0.0
  rotationy: -0.0
  rotationz: 0.0
  scalex: 1.0
  scaley: 1.0
  scalez: 1.0
  skirt_line_count: 3
  slicing_type: vip
  smooth_cmd: ./smooth_FASP.exe
  splanes_file: lib/planes_file.txt
  stl_file: example.stl
  stl_filename:
  t_geodesic: 0.0
  transformation_matrix:
    m00: 1.0
    m01: 0.0
    m02: 0.0
    m03: 0.0
    m10: 0.0
    m11: 1.0
    m12: 0.0
    m13: 0.0
    m20: 0.0
    m21: 0.0
    m22: 1.0
    m23: 0.0
    m30: 0.0
    m31: 0.0
    m32: 0.0
    m33: 1.0
  wall_thickness: 0.8
supports:
  enabled: true
  xy_offset: 1.0
  z_offset_layers: 1
  priority_z_offset: true
  fill_type: Lines
  fill_density: 5
  bottoms_depth: 0
  lids_depth: 0
uninterrupted_print:
  enabled: false
  cut_distance: 0.0
figures:
  - description: plane X0.00 Y0.00 Z0.00 T0.00 R0.00
    index: 0
    settings: {}
