name: Build executable
on:
  workflow_dispatch:
    inputs:
      id:
        description: "run identifier"
        required: false
jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event.inputs.id }}
        run: echo run ID ${{ github.event.inputs.id }}
      - name: Get current branch
        run: echo current branch ${{ github.ref }}
  build:
    runs-on: ${{ matrix.os }}
    container: node:16-buster
    strategy:
      matrix:
        os: [windows-latest, ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
      - name: Set lsb_release
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          apt-get update && apt-get install -y lsb-release && cat lsb_entry > /etc/lsb-release
      - name: Set up python 3.8 for ubuntu
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.16"
          cache: "pip"
      - name: Set up python 3.10 for windows
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel flake8 pyinstaller
          python3 -m pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Run pyinstaller
        run: |
          pyinstaller main.spec
      - name: Copy additional files
        run: |
          mv settings.yaml dist/settings.yaml
          mv icon.png dist/icon.png
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "spycer-${{ matrix.os }}"
          path: |
            dist/
