name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff==0.3.3
      - name: Run Ruff
        run: ruff format --diff .
      - name: Run tests
        run: |
          python -m unittest discover -s test -p '*_test.py'
